version: "3.8"
services:
  webapp:
    build: ./
    image: app
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
    depends_on:
      - rabbitmq
      - celery
      - postgres

# postgres docker 임시 사용
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mlc
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data

  rabbitmq:
    image: rabbitmq:3.7-alpine
    command: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery:
    build: ./
    command: celery -A app.mlc.services worker -P gevent --concurrency=20 -l info
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_BACKEND_URL=db+postgresql://admin:admin@postgres:5432/mlc
    depends_on:
      - rabbitmq