apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: mlc-container
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 500m
      memory: 0.5Gi
    default:
      cpu: "1"
      memory: 1.5Gi


